# Add a "/" at the start of the topics to avoid namespacing
# The frame_ids are automatically namespaced in the rgbd.launch.py file.
# If the robot namespace is "robot_0" then the frame_ids become "robot_0/camera_link"

ORB_SLAM3_RGBD_ROS2:
  ros__parameters:
    # slam related
    robot_base_frame: base_footprint
    global_frame: map
    odom_frame: odom


    rgb_image_topic_name: /world/z_simple_palm_plantation/model/x500_custom_0/link/rgbd_link/sensor/rgbd/image
    depth_image_topic_name: /world/z_simple_palm_plantation/model/x500_custom_0/link/rgbd_link/sensor/rgbd/depth_image
    imu_topic_name: imu #Not used in this variant. Try RGB_IMU to use this information.

    # the below parameters are used to adjust the initial pose with respect to the map. 
    # the camera pose maybe translated and rotated with respect to the base_footprint. The wrapper publishes map->base_footprint. Hence this relative transform needs to be accounted.
    # the below transform is the transform from base_footpring -> camera_link
    robot_x: 0.12     # Camera is 0.12m forward from base_link
    robot_y: 0.0      # Camera is centered (no Y offset)
    robot_z: 0.05     # Camera is 0.05m above base_link
    robot_qx: 0.0     # No rotation around X
    robot_qy: 0.173648   # Pitch about Y ≈ 20° (0.349066 rad)
    robot_qz: 0.0     # No rotation around Z
    robot_qw: 0.9848078  # cos(0.349066/2)

    visualization: true
    odometry_mode: false
    publish_tf: true
    map_data_publish_frequency: 1000 # publish every 1000.0 milliseconds
    do_loop_closing: true
